/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_eucalyptus_storage_AOEManager */

#ifndef _Included_com_eucalyptus_storage_AOEManager
#define _Included_com_eucalyptus_storage_AOEManager
#ifdef __cplusplus
extern "C" {
#endif
#undef com_eucalyptus_storage_AOEManager_MAX_MINOR_NUMBER
#define com_eucalyptus_storage_AOEManager_MAX_MINOR_NUMBER 16L
/*
 * Class:     com_eucalyptus_storage_AOEManager
 * Method:    exportVolume
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_eucalyptus_storage_AOEManager_exportVolume
  (JNIEnv *, jobject, jstring, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
