/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_eucalyptus_storage_OverlayManager_VolumeEntityWrapperManager */

#ifndef _Included_com_eucalyptus_storage_OverlayManager_VolumeEntityWrapperManager
#define _Included_com_eucalyptus_storage_OverlayManager_VolumeEntityWrapperManager
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
