/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_eucalyptus_storage_OverlayManager */

#ifndef _Included_com_eucalyptus_storage_OverlayManager
#define _Included_com_eucalyptus_storage_OverlayManager
#ifdef __cplusplus
extern "C" {
#endif
#undef com_eucalyptus_storage_OverlayManager_MAX_LOOP_DEVICES
#define com_eucalyptus_storage_OverlayManager_MAX_LOOP_DEVICES 256L
#undef com_eucalyptus_storage_OverlayManager_LVM_HEADER_LENGTH
#define com_eucalyptus_storage_OverlayManager_LVM_HEADER_LENGTH 4194304LL
/*
 * Class:     com_eucalyptus_storage_OverlayManager
 * Method:    registerSignals
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_eucalyptus_storage_OverlayManager_registerSignals
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
